#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Values that don't change per machine.
GCP_PROJECT=1034667055128  # the Cloud project from issue #43 (web + Google sign-in)
APP_ID=com.budjetame.android
UPLOAD_SHA1="268C:3909:ECC4:C8D1:5574:1045:DDB4:3DE2:0ADA:AEAD"  # issue #43's release key
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# The two properties go to the user-level gradle.properties: the repo's
# gradle.properties is tracked, and a key must never be committed.
ENV_FILE="${HOME}/.gradle/gradle.properties"
mkdir -p "$(dirname "$ENV_FILE")"

banner "Google Maps picker — production setup"

# ── Stage 1: confirm the Cloud project ────────────────────────────────────
stage "Google Cloud project"
say "The map key lives in the same Google Cloud project as the web app and"
say "Google sign-in: project number ${GCP_PROJECT}."
open_url "https://console.cloud.google.com/home/dashboard?project=${GCP_PROJECT}"
step "Confirm the project picker (top-left) shows the Budjetame project."
step "If a different project opened, select Budjetame (or the project from"
step "     issue #43) in the picker."
pause "Right project selected?"

# ── Stage 2: enable the two APIs ──────────────────────────────────────────
stage "Enable Maps SDK for Android + Places API"
say "Both APIs are free to enable; billing only starts when the app calls them."
open_url "https://console.cloud.google.com/apis/library/maps-android-backend.googleapis.com?project=${GCP_PROJECT}"
step "Click 'Enable' (it reads 'Manage' if the API is already on)."
pause "Maps SDK for Android enabled?"
open_url "https://console.cloud.google.com/apis/library/places-backend.googleapis.com?project=${GCP_PROJECT}"
step "Click 'Enable' on the Places API page too."
note "The app uses the Places SDK's legacy path (Places.initialize + the"
note "Autocomplete widget), so it needs this legacy Places API — the web app"
note "already uses it in this project. Places API (New) only becomes relevant"
note "after a code migration to initializeWithNewPlacesApiEnabled()."
pause "Places API enabled?"

# ── Stage 3: billing ──────────────────────────────────────────────────────
stage "Billing account"
warn "Android map loads and place searches are paid SKUs with their own free"
warn "monthly calls — a runaway key is a bill. Watch the cost page."
open_url "https://console.cloud.google.com/billing/linked?project=${GCP_PROJECT}"
step "If a billing account is already linked (the web Maps key uses one),"
step "     continue."
step "Otherwise click 'Link a billing account' and follow the flow."
step "Recommended: set a budget alert at the page below."
open_url "https://console.cloud.google.com/billing/budgets?project=${GCP_PROJECT}"
pause "Billing linked (and a budget alert set)?"

# ── Stage 4: the two signing fingerprints ─────────────────────────────────
stage "Signing fingerprints"
say "Maps authorizes the app by package name + signing-certificate SHA-1."
say "Play re-signs every release with its own key, so a Play install and a"
say "sideloaded release APK carry DIFFERENT certificates — register both:"
note "  Play installs:       the app signing key, from the Play Console"
note "  sideloaded release:  the upload key, ${UPLOAD_SHA1}"
open_url "https://play.google.com/console"
step "Open the Budjetame app → Test and release → Setup → App signing."
step "Copy the SHA-1 under 'App signing key certificate'."
ask APP_SIGNING_SHA1 "Paste the app signing SHA-1 (AB:CD:...):"
confirm "Also authorize debug/emulator builds?" && {
  step "Run ./gradlew signingReport in ${REPO_ROOT} and copy the debug SHA-1"
  step "     when the key page asks; it signs with ~/.android/debug.keystore."
  DEBUG_MAPS=yes
} || DEBUG_MAPS=no

# ── Stage 5: create and restrict the key ──────────────────────────────────
stage "Create the API key"
say "Now create the key the Android app sends with every map request. The web"
say "key cannot be reused: it is restricted to HTTP referrers."
open_url "https://console.cloud.google.com/apis/credentials?project=${GCP_PROJECT}"
step "Click 'Create credentials' → 'API key' and copy the AIza... value."
ask_secret GOOGLE_MAPS_API_KEY "Paste the API key:"
step "On the key page, click 'Edit API key' (or its name in the list)."
step "Under 'Application restrictions' choose 'Android apps'."
step "Add the package name: ${APP_ID}"
step "Add these SHA-1 fingerprints:"
note "  app signing (Play):    ${APP_SIGNING_SHA1:-<the Play Console value>}"
note "  upload key (sideload): ${UPLOAD_SHA1}"
if [[ "$DEBUG_MAPS" == yes ]]; then
  step "Also add the debug SHA-1 that ./gradlew signingReport prints."
fi
step "Under 'API restrictions' choose 'Restrict key' and tick only:"
note "  Maps SDK for Android · Places API   (not 'Places API (New)')"
step "Click 'Save'. Restrictions take about five minutes to propagate."
pause "Key created, restricted, and saved?"

# ── Stage 6: switch the build and verify ──────────────────────────────────
stage "Switch the build to Google Maps"
say "Production builds read the provider and key from Gradle properties at"
say "build time — user-level ${ENV_FILE}, never the tracked repo file."
write_env MAP_PROVIDER google
write_env GOOGLE_MAPS_API_KEY "$GOOGLE_MAPS_API_KEY"
note "Both apply to every build on this machine, debug included: pass"
note "-PMAP_PROVIDER=leaflet to keep the free picker in a debug build."
note "A 'google' build with no key fails loudly at render time by design."
if [[ -z "$(_existing RELEASE_KEYSTORE_PATH || true)" ]]; then
  warn "No RELEASE_KEYSTORE_PATH in ${ENV_FILE}: assembleRelease comes out"
  warn "unsigned and cannot be installed for verification (see the README)."
fi
confirm "Build a signed release APK now?" && {
  step "Running ./gradlew assembleRelease ..."
  (cd "$REPO_ROOT" && ./gradlew assembleRelease) \
    || warn "the build failed — fix it, then re-run ./gradlew assembleRelease"
}
step "Install app/build/outputs/apk/release/app-release.apk on a device."
step "Open a Transaction's location picker and verify:"
note "  the map renders with no 'authorization failure' watermark"
note "  search opens autocomplete; a pick carries the place name"
note "  a POI tap fills the name; a bare-map tap stays coordinates-only"
warn "The sideload is authorized by the upload-key SHA-1; Play installs use"
warn "the app signing SHA-1. Verify an internal-testing track build too."
pause "Google Maps verified on a release build?"
# ──────────────────────────────────────────────────────────────────────────

finish
